### PR TITLE
Added links in attachments support

### PR DESCRIPTION
**Pull request by fedirkh**
If you have any suggestions about code style, please tell me.

### CODE REVIEW

**Comment by orliesaurus** [comment]
Cool, would love to see some tests maybe 👍

**Comment by orliesaurus** [comment]
additionally, why are you using "co" ?  wouldn't it be better to use async await (just for an example of the clean feeling watch this: https://medium.com/@Abazhenov/using-async-await-in-express-with-node-8-b8af872c0016 )

**Comment by superiority** [comment]
async-await operators are cool, but they're supported only from node v7, and it will break compatibility for earlier node versions. I think a lot of people needs this in node < 7, at least I need :)
I propose to leave co in 1.4.0 (because co doesn't supported by node < 4) package version, and replace it by async-await in, maybe, 1.5.0 or 2.0.0, to not break compatibility. 
What do you think about this?

**Comment by orliesaurus** [comment]
I think that's OK I just have to do it out of catch up on this module and I will merge this as soon as I get a chance and to publish it afterwards

**Comment by henrinormak** [comment]
Any update on this? This would close #16 IIRC

**Comment by fedirkh** [comment]
Repo code was changed dramatically since PR opening, so this task should be done from scratch now I guess

**Pull request closed without merging**
