### PR TITLE
Fixed attachments

### PR DESCRIPTION
**Pull request by havokentity**
Fixed attachments to work and conforming to nodemailer "attachments" instead of "attachment"

@orliesaurus Hope this helps!

### CODE REVIEW

**Comment by jonathanprl** [comment]
I've already opened an almost identical pull request. :laugh:

https://github.com/orliesaurus/nodemailer-mailgun-transport/pull/35

**Comment by orliesaurus** [comment]
make my life easy and tell me which one to merge i'm on an airplane right now 🎯

**Comment by jonathanprl** [comment]
I've updated the tests on mine, so I guess mine?

**Comment by havokentity** [comment]
Haha, just saw, yeah guess Jonathans'

On Fri, Jul 1, 2016 at 12:50 PM, Jonathan Lambert <notifications@github.com>
wrote:

> I've updated the tests on mine, so I guess mine?
>
> On Fri, 1 Jul 2016 05:16 orliesaurus, <notifications@github.com> wrote:
>
> > make my life easy and tell me which one to merge i'm on an airplane right
> > now 🎯
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/orliesaurus/nodemailer-mailgun-transport/pull/38#issuecomment-229850287
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABbMfCbaCwTG668i0btbVW6whskmB93Mks5qRJStgaJpZM4JBz0J
> >
> > .
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/orliesaurus/nodemailer-mailgun-transport/pull/38#issuecomment-229874326>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB3YxTjFiy-NmXwgVyEcIM5phfYp-eMXks5qRL-4gaJpZM4JBz0J>
> .
>



-- 
-
Rajesh Peter Douglas D'Monte

http://www.rajeshdmonte.com/

**Comment by orliesaurus** [comment]
Okay boys! :)

**Comment by jonathanprl** [comment]
@orliesaurus Thanks. I updated the tests in mine by the way #35, if you haven't done so yourself already.

**Pull request merged**
