### PR TITLE
add address objects support

### PR DESCRIPTION
**Pull request by ADumaine**
Address can be an object or array of objects with the keys 'name' and
'address'.

### CODE REVIEW

**Comment by ADumaine** [comment]
Would it be possible to get this pull request reviewed and merged?

Thanks,

**Comment by orliesaurus** [comment]
Aye captain, does it break anything? Did you test it?

**Comment by ADumaine** [comment]
I ran the existing test and it passed. but I did not add any specific test for an address object.  I am currently using it in a project that is about to be deployed and have not encountered any issues.

**Comment by orliesaurus** [comment]
Thank you for your contribution to this mail🔫  module @ADumaine - may the force be with you 🙏

**Pull request merged**
