### PR TITLE
Vulnerability fix : bump mailgun-js

### PR DESCRIPTION
**Pull request by Ilshidur**
This fixes 3 [known vulnerabilities](https://snyk.io/test/npm/nodemailer-mailgun-transport/1.3.5) which are :

* 2 Regular Expression Denial of Service vulnerability
* 1 Uninitialized Memory Exposure

By bumping the [mailgun-js](https://www.npmjs.com/package/mailgun-js) package (from [`0.7.10`](https://snyk.io/test/npm/mailgun-js/0.7.10) to [`0.13.1`](https://snyk.io/test/npm/mailgun-js/0.13.1)), all these vulnerabilities get fixed because they were all caused by this underlying package.

### CODE REVIEW

**Comment by orliesaurus** [comment]
Cheers!

**Comment by Ilshidur** [comment]
Is it possible to have a release cut for this fix ? Thanks !

**Comment by orliesaurus** [comment]
what's a release "cut"?

**Comment by Ilshidur** [comment]
Oops sorry for my english.
I meant "cut a release" for the changes of this PR, so everyone can access the fix on npm :-)

**Comment by orliesaurus** [comment]
Oh yeah that makes sense - I've published them on npm now 👍 do you know if there's a simple way to directly publish from github to npm? that would be neat!

**Comment by Ilshidur** [comment]
Great ! Thanks.
As far as I know, I don't think there is an existing tool for this. If I find something, I'll let you know.

**Pull request merged**
