### PR TITLE
adding recipient-variables

### PR DESCRIPTION
**Pull request by crossman**
This is needed to be able to send batched emails

### CODE REVIEW

**Comment by stevepaulo** [comment]
Can you merge the latest upstream changes? Then we can merge this in.

**Comment by crossman** [comment]
Done

**Comment by TheCrow1213** [comment]
Hey guys, is there a quick example somewhere of a correct request including recipient-variables? Having issues getting this to work. Here's my model:

```
    emailModel = {
        to: ['email1@gmail.com', 'email2@gmail.com'],
        'recipient-variables': {
            "email1@gmail.com": { 'id': '0' },
            "email2@gmail.com": { 'id': '1' },
        }
    };
```

**Comment by crossman** [comment]
That's how I'm using it. I'd recommend taking a look at mailgun's docs if that's not working for you.

**Comment by TheCrow1213** [comment]
For some reason it is working now! I wonder if mailgun was just acting strange. I could have done something dumb as well. ¯\_(ツ)_/¯ Thanks!

**Pull request merged**
