### PR TITLE
Support all the options Mailgun supports

### PR DESCRIPTION
**Pull request by holm**
This PR adds support for passing all the options to Mailgun that it supports. 

The full list of data supported can be found here: https://documentation.mailgun.com/api-sending.html#sending

This uses a few lodash functions, that could probably be inlined, but since the dependencies are tiny, I felt this is the cleaner way to do it.

### CODE REVIEW

**Comment by holm** [comment]
Since I kept making a few mistakes, I added some simple tests also.

**Comment by holm** [comment]
I also added a travis file to test on older node versions down to 0.10.

**Comment by orliesaurus** [comment]
thanks @holm - super appreciated

**Comment by holm** [comment]
Thanks. I would encourage you to enable Travis CI for this repo, so new commits and PR's are automatically tested. It's free for open source projects: https://travis-ci.org/

**Comment by orliesaurus** [comment]
Yeah I know its a thing in the open source world, hopefully this weekend if the weather is ugly enough :)

**Comment by holm** [comment]
Any chance you could release a version? Would like to get back to the main release, and off my branch :) Thanks.

**Comment by orliesaurus** [comment]
oh I thought I did, I must have forgotten! Let me do it asap

**Comment by orliesaurus** [comment]
done - thanks

**Pull request merged**
